### ISSUE TITLE
Support array like query param as repeating query key

### ISSUE THREAD

**Issue by psamusev** [karlvr/openapi-generator-plus-generators#12]
if we have query which can be either standalone value of array of values, pass them to the query param as repeating key and item value
```
context=firts-level-context-id&context=second-level-context-id
```

UrlSearchParams support multiple append for the same key, like
```
const params = new URLSearchParams();
params.append('context', 'first-level-context-id');
params.append('context', 'second-level-context-id');
```
and automatically afterwards convert it to the correct query string

Also, worth to consider complex type item, i.e. each item of the array can be an object. For this we need stringify the value before appending
```
const params = new URLSearchParams();
params.append('context', JSON.stringify(obj1));
params.append('context', JSON.stringify(obj2);
```

**Comment by karlvr** [comment]
Thank you. Yes, I know I haven't done the right things there yet. I think this will affect every generator… are you particularly using the typescript-fetch-client?

**Comment by psamusev** [comment]
Personally me, yes, I'm using only `typescript-fetch-client`

**Comment by karlvr** [comment]
@psamusev I believe this should now be supported in `openapi-generator-plus@0.31.2` and `@openapi-generator-plus/typescript-fetch-client-generator@0.24.0`. If it doesn't work, could you please provide me with a minimal example schema so I can add a test and correct the issue!

**Comment by psamusev** [comment]
@karlvr Thanks for the updates. Testing of versions above lead me to some compilation error
![Screen Shot 2021-09-08 at 11 22 27 AM](https://user-images.githubusercontent.com/6784822/132473682-5687ec58-8801-4849-a258-941a564d4a4f.png)

**Comment by psamusev** [comment]
Schema to test
```
openapi: 3.0.0
paths:
  /api/list/{type}:
    get:
      operationId: TimerecordDetailController_getTimeRecordDetailList
      summary: ''
      description: Return list of particular time record detail
      parameters:
        - name: searchQuery
          required: false
          in: query
          description: Uses to filter out list items
          schema:
            type: string
        - name: context
          required: false
          in: query
          description: Uses to filter out list items
          schema:
            description: Array of context
            type: array
            items:
              $ref: '#/components/schemas/GetTimeRecordDetailsListContextQuery'
        - name: type
          required: true
          in: path
          example: client
          description: Type of requested time record detail list
          schema:
            type: string
      responses:
        '200':
          description: Time record detail list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimeRecordDetailsListResponse'
      tags:
        - Time record details
  
info:
  title: Timetracking API
  description: Defines backend contracts for timetracking pbc component
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: /
    description: Mock Nest JS based server implementation
components:
  schemas:
    BaseTimeRecordDetailValue:
      type: object
      properties:
        id:
          type: string
          description: Id of the provided value
          example: client-id-1
        label:
          type: string
          description: Label of the provided value
          example: Big Client
      required:
        - id
        - label
    TimeRecordDetail:
      type: object
      properties:
        type:
          type: string
          description: Unique detail type. Should be mapped to the time record detail type
          example: client
        value:
          description: Particular detail value
          allOf:
            - $ref: '#/components/schemas/BaseTimeRecordDetailValue'
      required:
        - type
        - value
    GetTimeRecordDetailsListContextQuery:
      type: object
      properties:
        type:
          type: string
          description: Time record detail type
          example: client
        value:
          type: string
          description: Unique identifier of the time record detail value
          example: client-id-1
      required:
        - type
        - value
    GetTimeRecordDetailsListResponse:
      type: object
      properties:
        items:
          description: List of particular time record detail type
          example:
            - id: client-id-0
              label: John Doe
            - id: client-id-1
              label: Big Client
          type: array
          items:
            $ref: '#/components/schemas/BaseTimeRecordDetailValue'
      required:
        - items
```

**Comment by karlvr** [comment]
@psamusev could you please try upgrading? There was an issue with needing to generate different parameter names to avoid reserved words, sometimes, that caused this not to generate the correct code. It shouldn't be a problem in the latest release though!

The code generated is more like:

```typescript
if (context !== undefined) {
	/* array form exploded */
	for (const localVarArrayElement of context) {
		if (localVarArrayElement !== undefined) {
			localVarQueryParameter.append('context', localVarArrayElement !== null ? [
			localVarArrayElement["type"] !== undefined ? localVarArrayElement["type"] !== null ? `aType,${String(localVarArrayElement["type"])}` : 'aType,' : undefined, 
			localVarArrayElement["value"] !== undefined ? localVarArrayElement["value"] !== null ? `value,${String(localVarArrayElement["value"])}` : 'value,' : undefined 
			].filter(localVarObjectElement => localVarObjectElement !== undefined).join(','): '');
		}
	}
}
```

**Comment by psamusev** [comment]
@karlvr Tested the last version. Everything works as expected, thanks! You can close the issue

**Comment by karlvr** [comment]
@psamusev OK, thank you. Firstly, that `aType` is due to more faulty reserved-word handling. I've pushed a fix for that.

Secondly, my implementation of https://swagger.io/specification/#style-examples using the default mode in a query of `style: form` and `explode: true` led me to explode your `context` array, so you get a separate `context` in the `URLSearchParams` for each entry, but _not_ to explode the object within the array.

I think this works perfectly for any _non_ object type in an array. I think it works correctly for a nested array too; the top-level would be separate query params (exploded) but the second-level would be comma-separated, e.g. `[[1,2,3],[4,5,6]]` serialises as `firstlevel=1,2,3&fistlevel=4,5,6`.

What to do for an array containing objects? It appears not be defined by the spec! Also refer https://stackoverflow.com/questions/67745944/openapi-path-query-parameters-nested-structure-serialization. You've said that you'd expect a JSON serialisation of the object, which seems reasonable, but I don't think that's supported in the specification?

With the latest code you'll end up with `context=type,client,value,client-id-1`, which is my interpretation of the spec; using `form` style and `explode` for the array, and then `form` style with no `explode` for the object.

As I think we're in an undefined space of the spec, this seems like room for vendor extensions to save us...

**Comment by karlvr** [comment]
@psamusev thank you very much for sticking with me! I've added a vendor extension `x-serialize-nested-as-json` that you can add to a parameter to get the desired behaviour (I hope). I'll push a new release shortly.

I've taken the liberty of including your example schema in two test cases; I hope you don't mind. Please let me know if you'd like me to obfuscate it.

An example:

```yml
        - name: context
          required: false
          in: query
          description: Uses to filter out list items
          x-serialize-nested-as-json: true
          schema:
            description: Array of context
            type: array
            items:
              $ref: '#/components/schemas/GetTimeRecordDetailsListContextQuery'
```

Then the generated code is:

```typescript
if (context !== undefined) {
	/* array form exploded */
	for (const localVarArrayElement of context) {
		if (localVarArrayElement !== undefined) {
			localVarQueryParameter.append('context', localVarArrayElement !== null ? JSON.stringify(localVarArrayElement) : '');
		}
	}
}
```

**Comment by psamusev** [comment]
@karlvr thanks for clarification. Regarding JSON serialization, I've just followed the way how [swagger editor](https://editor.swagger.io/) is doing it. I assumed that we can use it as a source of truth regarding this particular case. Also may be useful to take a look at different scenarios here https://swagger.io/docs/specification/serialization/

**Comment by karlvr** [comment]
@psamusev thank you, I wilfully read over that content-in-parameter part after tackling `style` etc. It looks like _exactly_ what we need here.

I've implemented a lot of the `style` support, based on those examples. You can see what you were getting for your nested objects was based on the form/not-exploded mode. However I've only implemented support in the TypeScript client; not yet in any of the server implementations. There's always more work to do!

I'll take a crack at content-in-parameters support this morning and then remove that vendor extension.

**Comment by karlvr** [comment]
@psamusev looking again at schema-vs-content, it doesn't look like it does what you need in this case, as it would serialise your array to JSON, not the individual array components.

It does appear that editor.swagger.io serialises nested objects to JSON by default, so I'll change that to be my default as well, and remove the vendor extension. Done in the commit referenced just above. I've also fixed a few more things around the serialisation of parameters. Nearly there I think!

I haven't yet added the support for content-vs-schema.

**Comment by psamusev** [comment]
@karlvr Thanks you so much!. Regarding content vs schema, this not something that I need immediately, since You've added JSON Stringify as default behavior, but of course worth to have it in general, since it's defined by API
