### ISSUE TITLE
Support of bearer token type

### ISSUE THREAD

**Issue by psamusev** [karlvr/openapi-generator-plus-generators#13]
https://github.com/karlvr/openapi-generator-plus-generators/blob/master/packages/typescript-fetch-client/templates/api.hbs#L65 doesn't understand the bearer security type

Due to this task https://github.com/karlvr/openapi-generator-plus/issues/13, we can use the following check

```
			{{#ifeq scheme.name 'bearer'}}
			{{#if scheme.isHttp}}
			if (configuration && configuration.accessToken) {
				const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
					? configuration.accessToken("{{scheme.name}}")
					: configuration.accessToken;
				if (localVarAccessTokenValue !== null) {
					localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
				}
			}
			{{/if}}
			{{/ifeq}}
```

**Comment by karlvr** [comment]
I think what's happened is that I've actually _missed_ support for generic http authorisation. So I'm going to add that in... see what you think...

**Comment by karlvr** [comment]
Please take a look at 07e5d54b067eed5d2a326806b0feb0059145afe5, I think that will solve it, and generally for other http authorisations

**Comment by karlvr** [comment]
I've also taken the liberty of changing the name of the property in `ConfigurationParameters` that was previously just used for OAuth2 because I'm an animal.

**Comment by karlvr** [comment]
Thanks for raising the issue! I hope this closes it. I'll make another release soon.
